### ISSUE TITLE
Compiling shim on ClearLinux gives error

### ISSUE THREAD

**Issue by amshinde** [clearcontainers/shim#68] opened 2017-09-09 00:14 UTC
Compiling shim on clearlinux version 17650, gives the following error```
```
src/utils.c:67:2: error: ‘SIGUNUSED’ undeclared here (not in a function); did you mean ‘SI_USER’?
  SIGUNUSED,
  ^~~~~~~~~
```
Turns out that this constant has been removed in glib2.6 that clearlinux 17650 uses.
Ref: https://sourceware.org/git/?p=glibc.git;a=blob;f=NEWS;h=dd381f89308d850e0513cae935fb02adb094845a;hb=HEAD#l198

**Comment by gorozco1** [comment] 2017-09-09 03:45
I think this is duplicate of #65 and probably due a newer glibc

**Closed as completed** 2017-09-12 17:02 UTC
